server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    sampler:
      probability: 1
    host: 192.168.63.66
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart
    username: root
    password: root
  task:
    execution:
      thread-name-prefix: cart-async-
      pool:
        core-size: 100
        max-size: 200
        keep-alive: 60s
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 100
  rabbitmq:
    host: 192.168.63.66
    virtual-host: /lijunjietest
    username: lijunjie
    password: lijunjie
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 3
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
jwt:
  pubKeyPath: G:\sggjavastudy\200316\rsa\rsa.pub
  cookieName: GMALL_TOKEN
  userKeyName: user-key
  expire: 15552000
