server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
jwt:
  pubKeyPath: G:\sggjavastudy\200316\rsa\rsa.pub
  priKeyPath: G:\sggjavastudy\200316\rsa\rsa.pri
  secret: Ajdlskfpadfiuiqi;JPOIA&%&846579FUSJ;%9846af*^iodljf+565djda
  expire: 240
  cookieName: GMALL_TOKEN
  unick: unick
